/**

	AlarmListener.java

	The AlarmInterface defines the methods used to interact with an Alarm.

*/
public interface AlarmListener
{
	/**
	*	The takeNotice method is meant to respond to events associated with,
	*		or actions generated by, an Alarm.
	*/
	public void takeNotice();

}	//	end of interface AlarmListener